### ISSUE TITLE
Source has bitrotted, doesn't build

### ISSUE THREAD

**Issue by marvingreenberg** [tinrab/todo-angular-appengine#1]
This seems like a there is a lot of useful stuff here, but a simple attempt to clone and build is failing.  I'm building on OSX with node 11.10.

    $ node install
    <various...>

    c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' <...>  -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
    In file included from ../src/binding.cpp:1:
    In file included from ../../nan/nan.h:192:
    ../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
          return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);

There seem to be many issues like this (https://stackoverflow.com/questions/51886062/no-member-named-forceset, etc.) . I've upgrade to Node 11.10, which someone suggested as a fix.  But the failure is still occurring.   It is not completely clear what dependency is failing or why.

I'll do a pull request if I ever figure out what needs fixing or upgrading.

**Comment by marvingreenberg** [comment]
Adding an explicit dependency on a later version of sass seems to get rid of that build error,
    @@ -36,6 +38,7 @@
         "@types/jasmine": "~2.5.53",
         "@types/jasminewd2": "~2.0.2",
         "@types/node": "~6.0.60",
    +    "node-sass": "^4.11.0",
         "codelyzer": "~3.1.1",
         "jasmine-core": "~2.6.2",
         "jasmine-spec-reporter": "~4.1.0", 

But then, ng build is failing with various errors.

**Comment by tinrab** [comment]
I've fixed it by updating dependencies.

**Comment by marvingreenberg** [comment]
Perfect, thanks.  I'd gotten it all to run but was still having some issues with getting the material design stuff to "take effect" - obviously I'm new to all this.

**Comment by marvingreenberg** [comment]
I've been away, but this issue is resolved
